steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/notes-app-repo/notes-app','-f','Dockerfile','.']

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/notes-app-repo/notes-app']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/notes-app-repo/notes-app'

options:
  logging: CLOUD_LOGGING_ONLY
